# Site settings
title: Mareas de Tasajera
email: dteodoro33@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Esto es Mareas de Tasajera, una
  herramienta gratis para
  el monitoreo de la Isla Tasajera.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: @emana_sv
github_username:  danteo90

# Build settings
markdown: kramdown
